In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn import metrics
from sklearn import datasets

In [3]:
path = 'C:\\Users\\marim\\Desktop\\summer 2024 projects\\internship 2024\\data\\datasets\\'

In [4]:
df = pd.read_csv(path + 'MLP.csv')

In [5]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,3.242556,-2.387586,1.114630,0.661811,0.661811,-1.532615,1.532615,-0.794806,2.786572,-0.794806,-1.646611,-2.843570,0.0,1.5
1,2.838170,-2.652871,1.890054,0.506486,0.506486,-1.519456,1.519456,-0.765904,2.739344,-0.765904,-1.544162,-2.751697,0.0,2.5
2,2.387586,-3.242556,1.532615,0.794806,0.794806,-1.114630,1.646611,-0.661811,2.843570,-0.661811,-1.532615,-2.786572,1.5,0.0
3,2.741082,-2.899602,1.155879,0.726552,0.726552,-1.472919,1.750329,-0.726552,2.899602,-0.726552,-1.433289,-2.741082,1.5,1.0
4,2.899602,-2.741082,1.472919,0.726552,0.726552,-1.155879,1.433289,-0.726552,2.741082,-0.726552,-1.750329,-2.899602,1.0,1.5
5,2.739344,-2.751697,1.519456,0.506486,0.506486,-1.544162,1.890054,-0.765904,2.838170,-0.765904,-1.519456,-2.652871,1.5,2.0
6,2.899602,-2.741082,1.750329,0.726552,0.726552,-1.433289,1.155879,-0.726552,2.741082,-0.726552,-1.472919,-2.899602,1.0,2.5
7,2.652871,-2.838170,1.519456,0.765904,0.765904,-1.890054,1.544162,-0.506486,2.751697,-0.506486,-1.519456,-2.739344,2.5,0.0
8,2.741082,-2.899602,1.433289,0.726552,0.726552,-1.750329,1.472919,-0.726552,2.899602,-0.726552,-1.155879,-2.741082,2.5,1.0
9,2.751697,-2.739344,1.544162,0.765904,0.765904,-1.519456,1.519456,-0.506486,2.652871,-0.506486,-1.890054,-2.838170,2.0,1.5
10,2.786572,-2.843570,1.532615,0.661811,0.661811,-1.646611,1.114630,-0.794806,3.242556,-0.794806,-1.532615,-2.387586,2.5,2.0
11,2.843570,-2.786572,1.646611,0.794806,0.794806,-1.532615,1.532615,-0.661811,2.387586,-0.661811,-1.114630,-3.242556,2.0,2.5

In [6]:
col = df.columns
col[:12]

Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11'], dtype='object')

In [7]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,3.242556,-2.387586,1.114630,0.661811,0.661811,-1.532615,1.532615,-0.794806,2.786572,-0.794806,-1.646611,-2.843570,0.0,1.5
1,2.838170,-2.652871,1.890054,0.506486,0.506486,-1.519456,1.519456,-0.765904,2.739344,-0.765904,-1.544162,-2.751697,0.0,2.5
2,2.387586,-3.242556,1.532615,0.794806,0.794806,-1.114630,1.646611,-0.661811,2.843570,-0.661811,-1.532615,-2.786572,1.5,0.0
3,2.741082,-2.899602,1.155879,0.726552,0.726552,-1.472919,1.750329,-0.726552,2.899602,-0.726552,-1.433289,-2.741082,1.5,1.0
4,2.899602,-2.741082,1.472919,0.726552,0.726552,-1.155879,1.433289,-0.726552,2.741082,-0.726552,-1.750329,-2.899602,1.0,1.5

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       12 non-null     float64
 1   1       12 non-null     float64
 2   2       12 non-null     float64
 3   3       12 non-null     float64
 4   4       12 non-null     float64
 5   5       12 non-null     float64
 6   6       12 non-null     float64
 7   7       12 non-null     float64
 8   8       12 non-null     float64
 9   9       12 non-null     float64
 10  10      12 non-null     float64
 11  11      12 non-null     float64
 12  12      12 non-null     float64
 13  13      12 non-null     float64
dtypes: float64(14)
memory usage: 1.4 KB

In [9]:
df.describe()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
count,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000
mean,2.793644,-2.793644,1.509334,0.697019,0.697019,-1.509334,1.509334,-0.697019,2.793644,-0.697019,-1.509334,-2.793644,1.500000,1.500000
std,0.196199,0.196199,0.215787,0.098714,0.098714,0.215787,0.215787,0.098714,0.196199,0.098714,0.215787,0.196199,0.879049,0.879049
min,2.387586,-3.242556,1.114630,0.506486,0.506486,-1.890054,1.114630,-0.794806,2.387586,-0.794806,-1.890054,-3.242556,0.000000,0.000000
25%,2.740647,-2.857578,1.463011,0.661811,0.661811,-1.569774,1.463011,-0.765904,2.740647,-0.765904,-1.569774,-2.857578,1.000000,1.000000
50%,2.769134,-2.769134,1.526035,0.726552,0.726552,-1.526035,1.526035,-0.726552,2.769134,-0.726552,-1.526035,-2.769134,1.500000,1.500000
75%,2.857578,-2.740647,1.569774,0.765904,0.765904,-1.463011,1.569774,-0.661811,2.857578,-0.661811,-1.463011,-2.740647,2.125000,2.125000
max,3.242556,-2.387586,1.890054,0.794806,0.794806,-1.114630,1.890054,-0.506486,3.242556,-0.506486,-1.114630,-2.387586,2.500000,2.500000

In [10]:
# !pip install scikit-learn

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X = df[col[:12]]
y = df[col[12:]]

In [13]:
X

,0,1,2,3,4,5,6,7,8,9,10,11
0,3.242556,-2.387586,1.114630,0.661811,0.661811,-1.532615,1.532615,-0.794806,2.786572,-0.794806,-1.646611,-2.843570
1,2.838170,-2.652871,1.890054,0.506486,0.506486,-1.519456,1.519456,-0.765904,2.739344,-0.765904,-1.544162,-2.751697
2,2.387586,-3.242556,1.532615,0.794806,0.794806,-1.114630,1.646611,-0.661811,2.843570,-0.661811,-1.532615,-2.786572
3,2.741082,-2.899602,1.155879,0.726552,0.726552,-1.472919,1.750329,-0.726552,2.899602,-0.726552,-1.433289,-2.741082
4,2.899602,-2.741082,1.472919,0.726552,0.726552,-1.155879,1.433289,-0.726552,2.741082,-0.726552,-1.750329,-2.899602
5,2.739344,-2.751697,1.519456,0.506486,0.506486,-1.544162,1.890054,-0.765904,2.838170,-0.765904,-1.519456,-2.652871
6,2.899602,-2.741082,1.750329,0.726552,0.726552,-1.433289,1.155879,-0.726552,2.741082,-0.726552,-1.472919,-2.899602
7,2.652871,-2.838170,1.519456,0.765904,0.765904,-1.890054,1.544162,-0.506486,2.751697,-0.506486,-1.519456,-2.739344
8,2.741082,-2.899602,1.433289,0.726552,0.726552,-1.750329,1.472919,-0.726552,2.899602,-0.726552,-1.155879,-2.741082
9,2.751697,-2.739344,1.544162,0.765904,0.765904,-1.519456,1.519456,-0.506486,2.652871,-0.506486,-1.890054,-2.838170
10,2.786572,-2.843570,1.532615,0.661811,0.661811,-1.646611,1.114630,-0.794806,3.242556,-0.794806,-1.532615,-2.387586
11,2.843570,-2.786572,1.646611,0.794806,0.794806,-1.532615,1.532615,-0.661811,2.387586,-0.661811,-1.114630,-3.242556

In [14]:
y

     12   13
0   0.0  1.5
1   0.0  2.5
2   1.5  0.0
3   1.5  1.0
4   1.0  1.5
5   1.5  2.0
6   1.0  2.5
7   2.5  0.0
8   2.5  1.0
9   2.0  1.5
10  2.5  2.0
11  2.0  2.5

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

In [16]:
X_train

,0,1,2,3,4,5,6,7,8,9,10,11
5,2.739344,-2.751697,1.519456,0.506486,0.506486,-1.544162,1.890054,-0.765904,2.838170,-0.765904,-1.519456,-2.652871
2,2.387586,-3.242556,1.532615,0.794806,0.794806,-1.114630,1.646611,-0.661811,2.843570,-0.661811,-1.532615,-2.786572
1,2.838170,-2.652871,1.890054,0.506486,0.506486,-1.519456,1.519456,-0.765904,2.739344,-0.765904,-1.544162,-2.751697
11,2.843570,-2.786572,1.646611,0.794806,0.794806,-1.532615,1.532615,-0.661811,2.387586,-0.661811,-1.114630,-3.242556
4,2.899602,-2.741082,1.472919,0.726552,0.726552,-1.155879,1.433289,-0.726552,2.741082,-0.726552,-1.750329,-2.899602
7,2.652871,-2.838170,1.519456,0.765904,0.765904,-1.890054,1.544162,-0.506486,2.751697,-0.506486,-1.519456,-2.739344
3,2.741082,-2.899602,1.155879,0.726552,0.726552,-1.472919,1.750329,-0.726552,2.899602,-0.726552,-1.433289,-2.741082
6,2.899602,-2.741082,1.750329,0.726552,0.726552,-1.433289,1.155879,-0.726552,2.741082,-0.726552,-1.472919,-2.899602

In [17]:
X_test

,0,1,2,3,4,5,6,7,8,9,10,11
10,2.786572,-2.843570,1.532615,0.661811,0.661811,-1.646611,1.114630,-0.794806,3.242556,-0.794806,-1.532615,-2.387586
9,2.751697,-2.739344,1.544162,0.765904,0.765904,-1.519456,1.519456,-0.506486,2.652871,-0.506486,-1.890054,-2.838170
0,3.242556,-2.387586,1.114630,0.661811,0.661811,-1.532615,1.532615,-0.794806,2.786572,-0.794806,-1.646611,-2.843570
8,2.741082,-2.899602,1.433289,0.726552,0.726552,-1.750329,1.472919,-0.726552,2.899602,-0.726552,-1.155879,-2.741082

In [18]:
y_train

     12   13
5   1.5  2.0
2   1.5  0.0
1   0.0  2.5
11  2.0  2.5
4   1.0  1.5
7   2.5  0.0
3   1.5  1.0
6   1.0  2.5

In [19]:
y_test

     12   13
10  2.5  2.0
9   2.0  1.5
0   0.0  1.5
8   2.5  1.0

In [20]:
#training the model

In [21]:
from sklearn import neural_network

In [22]:
model = neural_network.MLPRegressor(hidden_layer_sizes=(24, 30), max_iter=100000, random_state=42)

In [23]:
model.fit(X_train, y_train)

MLPRegressor(hidden_layer_sizes=(24, 30), max_iter=100000, random_state=42)

In [24]:
y_pred = model.predict(X_test)
# y_pred

In [25]:
y = model.predict(X_train)
# y

In [26]:
# y_test

In [27]:
# tests MSE
mse = metrics.mean_squared_error(y_test, y_pred)
print("test MSE: ", mse)

test MSE:  1.0367856083886522

In [28]:
# train MSE
mse = metrics.mean_squared_error(y_train, y)
print("train MSE: ", mse)

train MSE:  0.03914884552007488

24 - 0.080, 0.815
25 - 0.040, 0.852

Hidden layer sizes:
17 - train MSE - 0.67
      test MSE - 0.63

19 - train MSE - 0.072
      test MSE - 0.909

20 - train MSE - 0.053 - improvement
      test MSE - 0.903

20, 5 - train MSE - 0.13 - increse
      test MSE - 0.64 - decrese 

20, 8 - train MSE - 0.06 - increse
      test MSE - 0.86 - decrese

20, 10 - train MSE - 0.049 - decrese
      test MSE - 0.959 - increse - overfitting

20, 15 - train MSE - 0.050 - decrese
      test MSE - 1.01 - increse - overfitting

21 - train MSE - 0.078 - 
      test MSE - 0.715

24 - train MSE - 0.069
      test MSE - 0.74

25 - train MSE - 0.06
      test MSE - 0.7

30 - train MSE - 0.03 - optimal
      test MSE - 0.87 - overfitting

30, 5 - train MSE - 0.049
          test MSE - 0.92

30, 7 - train MSE - 0.06
          test MSE - 0.91

30, 9 - train MSE - 0.01
          test MSE - 1.22 

30, 10 - train MSE - 0.04
          test MSE - 1.14 

35 - train MSE - 0.66 overfitting
      test MSE - 0.58

40 - train MSE - 0.70  This is overfitting
      test MSE - 0.61


If both errors decrease, you’re likely improving the model.
If training error decreases but validation error increases, the model is overfitting.
If both errors are high, the model may be underfitting.