In [4]:
import pandas as pd

In [25]:
path = 'C:\\Users\\marim\\Desktop\\summer 2024 projects\\internship 2024\\data\\datasets\\'

In [52]:
def reshape_df(br):
    df = pd.DataFrame()
    df = pd.read_csv(path+'Broken_VDLoc'+br+'.csv')
    # print(df)
    num_pairs = len(df) # for this instance it will be 12
    reshaped_data = df.values.reshape(-1, num_pairs * 2) #3
    # print(reshaped_data)
    reshaped_df = pd.DataFrame(reshaped_data, columns=column_names)
    return reshaped_df

In [58]:
df = reshape_df('')

In [49]:
# df = pd.read_csv(path + 'Broken_VDLoc.csv')
# # df = df.rename(columns={"Unnamed: 1": "correct"})

# df

    location   voltage
0        100  2.692306
1        200  2.692306
2        101  1.538461
3        102  0.769230
4        203  0.769230
5        210  1.538461
6        213  1.538461
7        220  0.769230
8        223  2.692306
9        130  0.769230
10       131  1.538461
11       132  2.692306

In [59]:
for i in br:
    # print(i)
    # df_new = pd.read_csv(path + 'Broken'+ i + '.csv') # read from csv FileExistsError
    df_new = reshape_df(i)
    print(df_new)
    # df = pd.merge(df, df_new, on="nodes")
    df = pd.concat([df, df_new], axis=0, ignore_index=True)

df

   Loc_1  voltage_1  Loc_2  voltage_2  Loc_3  voltage_3  Loc_4  voltage_4  \
0  100.0   3.242556  200.0   2.387586  101.0    1.11463  102.0   0.661811

   Loc_5  voltage_5  ...  Loc_8  voltage_8  Loc_9  voltage_9  Loc_10  \
0  203.0   0.661811  ...  220.0   0.794806  223.0   2.786572   130.0

   voltage_10  Loc_11  voltage_11  Loc_12  voltage_12
0    0.794806   131.0    1.646611   132.0     2.84357

[1 rows x 24 columns]
   Loc_1  voltage_1  Loc_2  voltage_2  Loc_3  voltage_3  Loc_4  voltage_4  \
0  100.0    2.83817  200.0   2.652871  101.0   1.890054  102.0   0.506486

   Loc_5  voltage_5  ...  Loc_8  voltage_8  Loc_9  voltage_9  Loc_10  \
0  203.0   0.506486  ...  220.0   0.765904  223.0   2.739344   130.0

   voltage_10  Loc_11  voltage_11  Loc_12  voltage_12
0    0.765904   131.0    1.544162   132.0    2.751697

[1 rows x 24 columns]
   Loc_1  voltage_1  Loc_2  voltage_2  Loc_3  voltage_3  Loc_4  voltage_4  \
0  100.0   2.387586  200.0   3.242556  101.0   1.532615  102.0   0.794806

   Loc_5  voltage_5  ...  Loc_8  voltage_8  Loc_9  voltage_9  Loc_10  \
0  203.0   0.794806  ...  220.0   0.661811  223.0    2.84357   130.0

   voltage_10  Loc_11  voltage_11  Loc_12  voltage_12
0    0.661811   131.0    1.532615   132.0    2.786572

[1 rows x 24 columns]
   Loc_1  voltage_1  Loc_2  voltage_2  Loc_3  voltage_3  Loc_4  voltage_4  \
0  100.0   2.741082  200.0   2.899602  101.0   1.155879  102.0   0.726552

   Loc_5  voltage_5  ...  Loc_8  voltage_8  Loc_9  voltage_9  Loc_10  \
0  203.0   0.726552  ...  220.0   0.726552  223.0   2.899602   130.0

   voltage_10  Loc_11  voltage_11  Loc_12  voltage_12
0    0.726552   131.0    1.433289   132.0    2.741082

[1 rows x 24 columns]
   Loc_1  voltage_1  Loc_2  voltage_2  Loc_3  voltage_3  Loc_4  voltage_4  \
0  100.0   2.739344  200.0   2.751697  101.0   1.519456  102.0   0.506486

   Loc_5  voltage_5  ...  Loc_8  voltage_8  Loc_9  voltage_9  Loc_10  \
0  203.0   0.506486  ...  220.0   0.765904  223.0    2.83817   130.0

   voltage_10  Loc_11  voltage_11  Loc_12  voltage_12
0    0.765904   131.0    1.519456   132.0    2.652871

[1 rows x 24 columns]
   Loc_1  voltage_1  Loc_2  voltage_2  Loc_3  voltage_3  Loc_4  voltage_4  \
0  100.0   2.899602  200.0   2.741082  101.0   1.472919  102.0   0.726552

   Loc_5  voltage_5  ...  Loc_8  voltage_8  Loc_9  voltage_9  Loc_10  \
0  203.0   0.726552  ...  220.0   0.726552  223.0   2.741082   130.0

   voltage_10  Loc_11  voltage_11  Loc_12  voltage_12
0    0.726552   131.0    1.750329   132.0    2.899602

[1 rows x 24 columns]
   Loc_1  voltage_1  Loc_2  voltage_2  Loc_3  voltage_3  Loc_4  voltage_4  \
0  100.0   2.899602  200.0   2.741082  101.0   1.750329  102.0   0.726552

   Loc_5  voltage_5  ...  Loc_8  voltage_8  Loc_9  voltage_9  Loc_10  \
0  203.0   0.726552  ...  220.0   0.726552  223.0   2.741082   130.0

   voltage_10  Loc_11  voltage_11  Loc_12  voltage_12
0    0.726552   131.0    1.472919   132.0    2.899602

[1 rows x 24 columns]
   Loc_1  voltage_1  Loc_2  voltage_2  Loc_3  voltage_3  Loc_4  voltage_4  \
0  100.0   2.652871  200.0    2.83817  101.0   1.519456  102.0   0.765904

   Loc_5  voltage_5  ...  Loc_8  voltage_8  Loc_9  voltage_9  Loc_10  \
0  203.0   0.765904  ...  220.0   0.506486  223.0   2.751697   130.0

   voltage_10  Loc_11  voltage_11  Loc_12  voltage_12
0    0.506486   131.0    1.519456   132.0    2.739344

[1 rows x 24 columns]
   Loc_1  voltage_1  Loc_2  voltage_2  Loc_3  voltage_3  Loc_4  voltage_4  \
0  100.0   2.741082  200.0   2.899602  101.0   1.433289  102.0   0.726552

   Loc_5  voltage_5  ...  Loc_8  voltage_8  Loc_9  voltage_9  Loc_10  \
0  203.0   0.726552  ...  220.0   0.726552  223.0   2.899602   130.0

   voltage_10  Loc_11  voltage_11  Loc_12  voltage_12
0    0.726552   131.0    1.155879   132.0    2.741082

[1 rows x 24 columns]
   Loc_1  voltage_1  Loc_2  voltage_2  Loc_3  voltage_3  Loc_4  voltage_4  \
0  100.0   2.786572  200.0    2.84357  101.0   1.532615  102.0   0.661811

   Loc_5  voltage_5  ...  Loc_8  voltage_8  Loc_9  voltage_9  Loc_10  \
0  203.0   0.661811  ...  220.0   0.794806  223.0   3.242556   130.0

   voltage_10  Loc_11  voltage_11  Loc_12  voltage_12
0    0.794806   131.0    1.532615   132.0    2.387586

[1 rows x 24 columns]
   Loc_1  voltage_1  Loc_2  voltage_2  Loc_3  voltage_3  Loc_4  voltage_4  \
0  100.0   2.751697  200.0   2.739344  101.0   1.544162  102.0   0.765904

   Loc_5  voltage_5  ...  Loc_8  voltage_8  Loc_9  voltage_9  Loc_10  \
0  203.0   0.765904  ...  220.0   0.506486  223.0   2.652871   130.0

   voltage_10  Loc_11  voltage_11  Loc_12  voltage_12
0    0.506486   131.0    1.890054   132.0     2.83817

[1 rows x 24 columns]
   Loc_1  voltage_1  Loc_2  voltage_2  Loc_3  voltage_3  Loc_4  voltage_4  \
0  100.0    2.84357  200.0   2.786572  101.0   1.646611  102.0   0.794806

   Loc_5  voltage_5  ...  Loc_8  voltage_8  Loc_9  voltage_9  Loc_10  \
0  203.0   0.794806  ...  220.0   0.661811  223.0   2.387586   130.0

   voltage_10  Loc_11  voltage_11  Loc_12  voltage_12
0    0.661811   131.0     1.11463   132.0    3.242556

[1 rows x 24 columns]

,Loc_1,voltage_1,Loc_2,voltage_2,Loc_3,voltage_3,Loc_4,voltage_4,Loc_5,voltage_5,...,Loc_8,voltage_8,Loc_9,voltage_9,Loc_10,voltage_10,Loc_11,voltage_11,Loc_12,voltage_12
0,100.0,2.692306,200.0,2.692306,101.0,1.538461,102.0,0.769230,203.0,0.769230,...,220.0,0.769230,223.0,2.692306,130.0,0.769230,131.0,1.538461,132.0,2.692306
1,100.0,3.242556,200.0,2.387586,101.0,1.114630,102.0,0.661811,203.0,0.661811,...,220.0,0.794806,223.0,2.786572,130.0,0.794806,131.0,1.646611,132.0,2.843570
2,100.0,2.838170,200.0,2.652871,101.0,1.890054,102.0,0.506486,203.0,0.506486,...,220.0,0.765904,223.0,2.739344,130.0,0.765904,131.0,1.544162,132.0,2.751697
3,100.0,2.387586,200.0,3.242556,101.0,1.532615,102.0,0.794806,203.0,0.794806,...,220.0,0.661811,223.0,2.843570,130.0,0.661811,131.0,1.532615,132.0,2.786572
4,100.0,2.741082,200.0,2.899602,101.0,1.155879,102.0,0.726552,203.0,0.726552,...,220.0,0.726552,223.0,2.899602,130.0,0.726552,131.0,1.433289,132.0,2.741082
5,100.0,2.739344,200.0,2.751697,101.0,1.519456,102.0,0.506486,203.0,0.506486,...,220.0,0.765904,223.0,2.838170,130.0,0.765904,131.0,1.519456,132.0,2.652871
6,100.0,2.899602,200.0,2.741082,101.0,1.472919,102.0,0.726552,203.0,0.726552,...,220.0,0.726552,223.0,2.741082,130.0,0.726552,131.0,1.750329,132.0,2.899602
7,100.0,2.899602,200.0,2.741082,101.0,1.750329,102.0,0.726552,203.0,0.726552,...,220.0,0.726552,223.0,2.741082,130.0,0.726552,131.0,1.472919,132.0,2.899602
8,100.0,2.652871,200.0,2.838170,101.0,1.519456,102.0,0.765904,203.0,0.765904,...,220.0,0.506486,223.0,2.751697,130.0,0.506486,131.0,1.519456,132.0,2.739344
9,100.0,2.741082,200.0,2.899602,101.0,1.433289,102.0,0.726552,203.0,0.726552,...,220.0,0.726552,223.0,2.899602,130.0,0.726552,131.0,1.155879,132.0,2.741082
10,100.0,2.786572,200.0,2.843570,101.0,1.532615,102.0,0.661811,203.0,0.661811,...,220.0,0.794806,223.0,3.242556,130.0,0.794806,131.0,1.532615,132.0,2.387586
11,100.0,2.751697,200.0,2.739344,101.0,1.544162,102.0,0.765904,203.0,0.765904,...,220.0,0.506486,223.0,2.652871,130.0,0.506486,131.0,1.890054,132.0,2.838170
12,100.0,2.843570,200.0,2.786572,101.0,1.646611,102.0,0.794806,203.0,0.794806,...,220.0,0.661811,223.0,2.387586,130.0,0.661811,131.0,1.114630,132.0,3.242556

In [26]:
broken = 'V01'
df = pd.read_csv(path+'Broken_VDLoc'+broken+'.csv')
df

    location   voltage
0        100  3.242556
1        200  2.387586
2        101  1.114630
3        102  0.661811
4        203  0.661811
5        210  1.532615
6        213  1.532615
7        220  0.794806
8        223  2.786572
9        130  0.794806
10       131  1.646611
11       132  2.843570

In [40]:
num_pairs = len(df)

print(num_pairs)

12

In [28]:
reshaped_data = df.values.reshape(-1, num_pairs * 2) #3
print(reshaped_data)

[[100.           3.24255574 200.           2.3875863  101.
    1.11462967 102.           0.6618111  203.           0.6618111
  210.           1.53261473 213.           1.53261473 220.
    0.79480635 223.           2.78657204 130.           0.79480635
  131.           1.64661065 132.           2.84357   ]]

In [42]:
column_names = []
for i in range(num_pairs):
    # column_names.append(f'VD_{i+1}')
    column_names.append(f'Loc_{i+1}')
    column_names.append(f'voltage_{i+1}')

column_names

['Loc_1',
 'voltage_1',
 'Loc_2',
 'voltage_2',
 'Loc_3',
 'voltage_3',
 'Loc_4',
 'voltage_4',
 'Loc_5',
 'voltage_5',
 'Loc_6',
 'voltage_6',
 'Loc_7',
 'voltage_7',
 'Loc_8',
 'voltage_8',
 'Loc_9',
 'voltage_9',
 'Loc_10',
 'voltage_10',
 'Loc_11',
 'voltage_11',
 'Loc_12',
 'voltage_12']

In [31]:
reshaped_df = pd.DataFrame(reshaped_data, columns=column_names)

reshaped_df

,Loc_1,voltage_1,Loc_2,voltage_2,Loc_3,voltage_3,Loc_4,voltage_4,Loc_5,voltage_5,...,Loc_8,voltage_8,Loc_9,voltage_9,Loc_10,voltage_10,Loc_11,voltage_11,Loc_12,voltage_12
0,100.0,3.242556,200.0,2.387586,101.0,1.11463,102.0,0.661811,203.0,0.661811,...,220.0,0.794806,223.0,2.786572,130.0,0.794806,131.0,1.646611,132.0,2.84357

In [34]:
br = ['V01', 'V02', 'H10', 'H11', 'H12', 'V11', 'V12', 'H20', 'H21', 'H22', 'V21', 'V22'] 
# br = ['101', '102', '210', '211', '212', '111', '112', '220', '221', '222', '121', '122']

In [60]:
df

,Loc_1,voltage_1,Loc_2,voltage_2,Loc_3,voltage_3,Loc_4,voltage_4,Loc_5,voltage_5,...,Loc_8,voltage_8,Loc_9,voltage_9,Loc_10,voltage_10,Loc_11,voltage_11,Loc_12,voltage_12
0,100.0,2.692306,200.0,2.692306,101.0,1.538461,102.0,0.769230,203.0,0.769230,...,220.0,0.769230,223.0,2.692306,130.0,0.769230,131.0,1.538461,132.0,2.692306
1,100.0,3.242556,200.0,2.387586,101.0,1.114630,102.0,0.661811,203.0,0.661811,...,220.0,0.794806,223.0,2.786572,130.0,0.794806,131.0,1.646611,132.0,2.843570
2,100.0,2.838170,200.0,2.652871,101.0,1.890054,102.0,0.506486,203.0,0.506486,...,220.0,0.765904,223.0,2.739344,130.0,0.765904,131.0,1.544162,132.0,2.751697
3,100.0,2.387586,200.0,3.242556,101.0,1.532615,102.0,0.794806,203.0,0.794806,...,220.0,0.661811,223.0,2.843570,130.0,0.661811,131.0,1.532615,132.0,2.786572
4,100.0,2.741082,200.0,2.899602,101.0,1.155879,102.0,0.726552,203.0,0.726552,...,220.0,0.726552,223.0,2.899602,130.0,0.726552,131.0,1.433289,132.0,2.741082
5,100.0,2.739344,200.0,2.751697,101.0,1.519456,102.0,0.506486,203.0,0.506486,...,220.0,0.765904,223.0,2.838170,130.0,0.765904,131.0,1.519456,132.0,2.652871
6,100.0,2.899602,200.0,2.741082,101.0,1.472919,102.0,0.726552,203.0,0.726552,...,220.0,0.726552,223.0,2.741082,130.0,0.726552,131.0,1.750329,132.0,2.899602
7,100.0,2.899602,200.0,2.741082,101.0,1.750329,102.0,0.726552,203.0,0.726552,...,220.0,0.726552,223.0,2.741082,130.0,0.726552,131.0,1.472919,132.0,2.899602
8,100.0,2.652871,200.0,2.838170,101.0,1.519456,102.0,0.765904,203.0,0.765904,...,220.0,0.506486,223.0,2.751697,130.0,0.506486,131.0,1.519456,132.0,2.739344
9,100.0,2.741082,200.0,2.899602,101.0,1.433289,102.0,0.726552,203.0,0.726552,...,220.0,0.726552,223.0,2.899602,130.0,0.726552,131.0,1.155879,132.0,2.741082
10,100.0,2.786572,200.0,2.843570,101.0,1.532615,102.0,0.661811,203.0,0.661811,...,220.0,0.794806,223.0,3.242556,130.0,0.794806,131.0,1.532615,132.0,2.387586
11,100.0,2.751697,200.0,2.739344,101.0,1.544162,102.0,0.765904,203.0,0.765904,...,220.0,0.506486,223.0,2.652871,130.0,0.506486,131.0,1.890054,132.0,2.838170
12,100.0,2.843570,200.0,2.786572,101.0,1.646611,102.0,0.794806,203.0,0.794806,...,220.0,0.661811,223.0,2.387586,130.0,0.661811,131.0,1.114630,132.0,3.242556

In [61]:
df.to_csv(path+'VDLoc.csv', index=False)